
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class ListUser extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public ListUser() {
        initComponents();
        getUser("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataUser = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        EditUser = new javax.swing.JButton();
        HapusUser = new javax.swing.JButton();
        TambahUser = new javax.swing.JButton();
        TxtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        DataUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DataUser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        DataUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "no", "username", "password", "role", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DataUser);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditUser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        EditUser.setText("Edit");
        EditUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserActionPerformed(evt);
            }
        });
        jPanel3.add(EditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 23, 87, 20));

        HapusUser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        HapusUser.setText("Hapus");
        HapusUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        HapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusUserActionPerformed(evt);
            }
        });
        jPanel3.add(HapusUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 23, 87, 20));

        TambahUser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        TambahUser.setText("Tambah");
        TambahUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahUserActionPerformed(evt);
            }
        });
        jPanel3.add(TambahUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 87, 20));

        TxtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCariActionPerformed(evt);
            }
        });
        TxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariKeyReleased(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        HalamanPencarian hp = new HalamanPencarian(ListUser.this, true);
//        hp.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserActionPerformed
        int n = DataUser.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(DataUser.getValueAt(n, 0).toString());
            System.out.println(id);
             DashboardAdmin DA = new DashboardAdmin();
            EditUser U = new EditUser(DA, true);
            U.setId(id);
            U.loadData();
            U.setVisible(true); 
            System.out.println(U.getId());
        }
    }//GEN-LAST:event_EditUserActionPerformed

    private void HapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusUserActionPerformed
       try {
            int n = DataUser.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(DataUser.getValueAt(n, 0).toString());
            System.out.println(id);
//            String fullname = DataProduk.getValueAt(n, 1).toString();
            
            
            int opsi = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin menghapus data ?", 
                    "Hapus Data", 
                    JOptionPane.YES_NO_OPTION);
            if(opsi == 0){
                String Q = "DELETE FROM akun "
                        + "WHERE id_akun ="+id;
                
                try {
                    Connection K = Koneksi.Go();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    getUser(""); 
                    JOptionPane.showMessageDialog(this, "Data telah terhapus");
                } catch (SQLException e) {
                }
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        //        this.dispose();
    }//GEN-LAST:event_HapusUserActionPerformed

    private void TxtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtCariActionPerformed

    private void TxtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCariKeyReleased
        // TODO add your handling code here:
        String key = TxtCari.getText();
        String w = "WHERE username LIKE '%"+key+"%' "
        + "OR password LIKE '%"+key+"%' "
        + "OR role LIKE '%"+key+"%' ";
        getUser(w);
    }//GEN-LAST:event_TxtCariKeyReleased

    private void TambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahUserActionPerformed
        // TODO add your handling code here:
        DashboardAdmin DA = new DashboardAdmin();
        TambahUser tambahUserForm = new TambahUser(DA, true);
        tambahUserForm.setVisible(true);
    }//GEN-LAST:event_TambahUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getUser("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataUser;
    private javax.swing.JButton EditUser;
    private javax.swing.JButton HapusUser;
    private javax.swing.JButton TambahUser;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getUser(String Where) {
        DefaultTableModel model = new DefaultTableModel();
        
        // Menambahkan kolom ke dalam JTable
        model.addColumn("id");
        model.addColumn("no");
        model.addColumn("username");
        model.addColumn("password");
        model.addColumn("role");
        
        
        // Set model ke JTable
        DataUser.setModel(model);
        try {
            Connection conn = Koneksi.Go();
            String query = "SELECT * FROM akun "+Where; // Query untuk mengambil data user
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            int no = 0;
            // Ambil data dari ResultSet dan tambahkan ke JTable
            while (rs.next()) {
                int id = rs.getInt("id_akun");
                no++;
                String username = rs.getString("username");
                String Password = rs.getString("Password");
                String role = rs.getString("role");
                

                model.addRow(new Object[]{id,no,username, Password, role});
            }
            
            DataUser.getColumnModel().getColumn(0).setMinWidth(0);
            DataUser.getColumnModel().getColumn(0).setMaxWidth(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data: " + e.getMessage());
        }
    }
}
